version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.1
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: filebeat -e
